version: '3.7'

services:
  registry:
    image: registry:2.8.2
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "./auth:/auth"
      - "./registry:/var/lib/registry"
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"